enable_chaos_pod_delete      = true
enable_chaos_network_latency = true
enable_chaos_cpu_stress      = true
enable_chaos_disk_stress     = true
enable_chaos_memory_stress   = true
kube_config_path             = "/home/marco/.kube/k3s.yaml"
app_label                    = "app.kubernetes.io/name=wazuh-helm"
chaos_service_account        = "default"
project_id                   = "4581d17c-4795-44bd-9267-9fdc293dd1eb"
app_namespace                = "wazuh"
litmus_admin_password        = "LitmusAdmin!123"
litmus_admin_username        = "admin"
litmus_environment           = "k3sdev"
